# Generated by Django 5.0.3 on 2024-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person_Detail',
        ),
    ]
