# Generated by Django 5.0.3 on 2024-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_person_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Detail',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('aadhar_no', models.IntegerField()),
                ('pan_no', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=200)),
                ('date_of_addmission', models.DateField()),
                ('date_of_leaving', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('doc_aadhar', models.FileField(upload_to='')),
                ('doc_pan', models.FileField(upload_to='')),
                ('doc_tc', models.FileField(upload_to='')),
                ('doc_election', models.FileField(upload_to='')),
            ],
        ),
    ]
