# Generated by Django 5.0.3 on 2024-06-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person_detail',
            name='progress',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Waiting', 'Watiting'), ('Success', 'Success')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
