# Generated by Django 5.0.3 on 2024-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_detail_progress_person_detail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_detail',
            name='doc_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
